name: sci-sci
channels:
  - intel
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - asttokens=2.0.8
  - attrs=22.1.0
  - babel=2.10.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bat=0.21.0
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.1.0
  - click=8.1.3
  - cloudpickle=2.1.0
  - colorama=0.4.5
  - commonmark=0.9.1
  - conda=4.13.0
  - conda-package-handling=1.8.1
  - cryptography=37.0.4
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2022.8.0
  - dask-core=2022.8.0
  - dataclasses=0.8
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2022.8.0
  - entrypoints=0.4
  - executing=0.10.0
  - flit-core=3.7.1
  - fonttools=4.35.0
  - freetype=2.10.4
  - future=0.18.2
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glpk=4.65
  - gmp=6.2.1
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.9.0
  - intelpython=2022.1.0
  - ipykernel=6.14.0
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.1
  - jinja2=3.1.2
  - joblib=1.0.1
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.9.1
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=7.3.4
  - jupyter_core=4.11.1
  - jupyter_server=1.18.1
  - jupyterlab-fonts=2.0.0
  - jupyterlab-git=0.37.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.15.0
  - jupyterlab_widgets=1.1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libmamba=0.25.0
  - libmambapy=0.25.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libsodium=1.0.18
  - libsolv=0.7.22
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libuv=1.44.2
  - libwebp=1.2.3
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.12
  - locket=1.0.0
  - lxml=4.9.1
  - lz4=4.0.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mamba=0.25.0
  - markupsafe=2.1.1
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - metis=5.1.0
  - mistune=0.8.4
  - mpfr=4.1.0
  - msgpack-python=1.0.4
  - munkres=1.1.4
  - nbclassic=0.4.3
  - nbclient=0.6.6
  - nbconvert-core=6.5.3
  - nbconvert-pandoc=6.5.3
  - nbdime=3.1.1
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.8.5
  - nodejs=18.7.0
  - nomkl=1.0
  - notebook=6.4.12
  - notebook-shim=0.1.0
  - numexpr=2.8.3
  - numpy=1.23.2
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - orjson=3.7.3
  - packaging=21.3
  - pandas>=2
  - pandoc=2.19
  - pandocfilters=1.5.0
  - partd=1.3.0
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pkgutil-resolve-name=1.3.10
  - plotly=5.9.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow
  - pybind11-abi=4
  - pycosat=0.6.3
  - pycparser=2.21
  - pygments=2.13.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python_abi=3.9
  - pytz=2022.2.1
  - pyyaml=6.0
  - pyzmq=23.2.1
  - readline=8.1.2
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.28.1
  - rich=12.4.4
  - ruamel_yaml=0.15.80
  - scipy=1.9.0
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=65.0.1
  - six=1.16.0
  - smmap=3.0.5
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.2
  - stack_data=0.4.0
  - statsmodels=0.13.2
  - suitesparse=5.10.1
  - tbb=2021.5.0
  - tblib=1.7.0
  - tcl=8.6.10
  - tenacity=8.0.1
  - terminado=0.15.0
  - texttable=1.6.4
  - tinycss2=1.1.1
  - tk=8.6.12
  - tmux=3.3
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.3
  - wheel=0.37.1
  - widgetsnbextension=3.6.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - click-plugins==1.1.1
      - cligj==0.7.2
      - colorlog==6.6.0
      - coverage==6.4.2
      - cramjam==2.5.0
      - cython==0.29.32
      - dbgz==0.5.4
      - diptest==0.5.1
      - distfit==1.4.5
      - easydev==0.12.0
      - fastparquet==0.8.1
      - fiona==1.8.21
      - fitter==1.4.1
      - fsspec==2022.5.0
      - geojson==2.5.0
      - geopandas==0.11.1
      - iniconfig==1.1.1
      - jedi==0.17.2
      - jupyter-server==1.15.6
      - jupyterlab==3.3.4
      - jupyterlab-darkside-ui==0.2.3
      - jupyterthemes==0.20.0
      - lesscpy==0.15.0
      - mgzip==0.2.1
      - munch==2.5.0
      - nbconvert==5.6.1
      - parso==0.7.1
      - pbr==5.9.0
      - pip==22.2.2
      - pluggy==1.0.0
      - ply==3.11
      - pprintpp==0.4.0
      - py==1.11.0
      - pycountry==22.3.5
      - pycountry-convert==0.7.2
      - pypickle==1.1.0
      - pyproj==3.3.1
      - pytest==7.1.2
      - pytest-cov==3.0.0
      - pytest-mock==3.8.2
      - python-box==6.0.2
      - python-igraph==0.9.11
      - repoze-lru==0.7
      - scholarmetrics==0.2.1
      - scikit-learn==1.1.2
      - shapely==1.8.2
      - threadpoolctl==3.1.0
      - ujson==5.4.0

