name: min-sci-sci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mamba
  - orjson
  - ca-certificates
  - certifi
  - openssl
  - pandas
  - seaborn
  - pyarrow
  - fastparquet
  - ujson
  - python-box
  - unidecode
  - tqdm
  - requests
  - seaborn
